# Generated by Django 5.2.8 on 2025-11-19 18:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, verbose_name='Agent Name')),
                ('action', models.CharField(max_length=255, verbose_name='Action Taken')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Details')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('agent_name', models.CharField(max_length=100, verbose_name='Target Agent')),
                ('task_type', models.CharField(max_length=100, verbose_name='Task Type')),
                ('payload', models.JSONField(default=dict, verbose_name='Task Data')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('result', models.TextField(blank=True, null=True, verbose_name='Task Result')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
