#!/bin/bash
# 🚀 Final SSL Setup - Manual Commands for User to Run

echo "🎉 EXCELLENT! Let's Encrypt successfully issued certificates for fan-club.kz!"
echo "========================================================================"
echo ""
echo "Let's Encrypt certificates are already available at:"
echo "• Certificate: /etc/letsencrypt/live/fan-club.kz-0001/fullchain.pem"
echo "• Private Key: /etc/letsencrypt/live/fan-club.kz-0001/privkey.pem"
echo ""
echo "🔧 To complete the SSL setup, please run these commands:"
echo "========================================================"
echo ""
echo "1. Create symlinks for nginx compatibility:"
echo "   sudo mkdir -p /etc/letsencrypt/live/fan-club.kz"
echo "   sudo ln -sf /etc/letsencrypt/live/fan-club.kz-0001/fullchain.pem /etc/letsencrypt/live/fan-club.kz/fullchain.pem"
echo "   sudo ln -sf /etc/letsencrypt/live/fan-club.kz-0001/privkey.pem /etc/letsencrypt/live/fan-club.kz/privkey.pem"
echo ""
echo "2. Set proper permissions:"
echo "   sudo chmod 644 /etc/letsencrypt/live/fan-club.kz/fullchain.pem"
echo "   sudo chmod 600 /etc/letsencrypt/live/fan-club.kz/privkey.pem"
echo ""
echo "3. Apply nginx SSL configuration:"
echo "   sudo cp /var/www/myapp/eventsite/nginx_http_only.conf /etc/nginx/nginx.conf.backup_ssl_manual"
echo "   sudo cp /var/www/myapp/eventsite/setup_ssl_nginx.sh /tmp/ && sudo bash /tmp/setup_ssl_nginx.sh"
echo ""
echo "ИЛИ просто выполните эту одну команду:"
echo "======================================"
echo ""
echo "sudo mkdir -p /etc/letsencrypt/live/fan-club.kz && sudo ln -sf /etc/letsencrypt/live/fan-club.kz-0001/fullchain.pem /etc/letsencrypt/live/fan-club.kz/fullchain.pem && sudo ln -sf /etc/letsencrypt/live/fan-club.kz-0001/privkey.pem /etc/letsencrypt/live/fan-club.kz/privkey.pem && sudo chmod 644 /etc/letsencrypt/live/fan-club.kz/fullchain.pem && sudo chmod 600 /etc/letsencrypt/live/fan-club.kz/privkey.pem && sudo cp /var/www/myapp/eventsite/setup_ssl_nginx.sh /tmp/ && sudo bash /tmp/setup_ssl_nginx.sh"
echo ""
echo "🎯 After running these commands, your site will have:"
echo "• ✅ Let's Encrypt SSL certificates (not self-signed!)"
echo "• ✅ HTTPS support on https://fan-club.kz"
echo "• ✅ Automatic HTTP to HTTPS redirect"
echo "• ✅ All AI features working perfectly"
echo "• ✅ Professional SSL security"
echo ""
echo "💡 Note: Let's Encrypt certificates automatically renew!"
echo ""
echo "🚀 Your SSL setup is almost complete - just need to run the commands above!"