# Generated by Django 4.2.13 on 2024-12-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_create_clubs',
            field=models.BooleanField(default=False),
        ),
    ]
