# Generated by Django 4.2.13 on 2024-12-21 06:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_can_create_clubs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[accounts.models.phone_regex_validator], verbose_name='Номер телефона'),
        ),
    ]
