# Generated by Django 5.2.8 on 2025-11-17 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_visit_completed',
            field=models.BooleanField(default=False, verbose_name='Первый визит завершен'),
        ),
        migrations.AddField(
            model_name='profile',
            name='welcome_chat_session_created',
            field=models.BooleanField(default=False, verbose_name='Приветственная сессия создана'),
        ),
    ]
