# Generated by Django 5.2.8 on 2025-11-17 20:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название услуги')),
                ('service_type', models.CharField(choices=[('rental', 'Аренда оборудования'), ('printing', 'Печать и вышивка'), ('consultation', 'Консультации специалистов'), ('studio', 'Студия интервью'), ('merchandise', 'Сувенирная продукция')], max_length=20, verbose_name='Тип услуги')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_info', models.CharField(blank=True, max_length=500, verbose_name='Информация о цене')),
                ('contact_info', models.CharField(blank=True, max_length=200, verbose_name='Контактная информация')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Услуга платформы',
                'verbose_name_plural': 'Услуги платформы',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InterviewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=200, verbose_name='Название проекта')),
                ('project_description', models.TextField(verbose_name='Описание проекта')),
                ('preferred_dates', models.CharField(max_length=200, verbose_name='Предпочтительные даты')),
                ('contact_info', models.CharField(max_length=200, verbose_name='Контактная информация')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассмотрения'), ('approved', 'Одобрена'), ('scheduled', 'Запланирована'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_requests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка на интервью',
                'verbose_name_plural': 'Заявки на интервью',
                'ordering': ['-created_at'],
            },
        ),
    ]
