# Generated by Django 5.2.8 on 2025-11-17 20:32

from django.db import migrations


def create_initial_platform_services(apps, schema_editor):
    """
    Создает начальные услуги платформы
    """
    PlatformService = apps.get_model('ai_consultant', 'PlatformService')

    services = [
        {
            'title': 'Аренда звукового оборудования',
            'service_type': 'rental',
            'description': 'Профессиональное звуковое оборудование для мероприятий: микрофоны, колонки, микшеры',
            'price_info': 'от 5 000 тг/час',
            'contact_info': 'rental@fan-club.kz',
            'order': 1
        },
        {
            'title': 'Аренда светового оборудования',
            'service_type': 'rental',
            'description': 'Современное световое оборудование для создания атмосферы на мероприятиях',
            'price_info': 'от 3 000 тг/час',
            'contact_info': 'rental@fan-club.kz',
            'order': 2
        },
        {
            'title': 'Печать логотипов на одежде',
            'service_type': 'printing',
            'description': 'Качественная печать логотипов и дизайна на футболках, толстовках, бейсболках',
            'price_info': 'от 2 000 тг/шт',
            'contact_info': 'print@fan-club.kz',
            'order': 3
        },
        {
            'title': 'Вышивка логотипов',
            'service_type': 'printing',
            'description': 'Профессиональная вышивка логотипов на кепках, одежде и текстильных изделиях',
            'price_info': 'от 1 500 тг/шт',
            'contact_info': 'print@fan-club.kz',
            'order': 4
        },
        {
            'title': 'Изготовление баннеров',
            'service_type': 'printing',
            'description': 'Печать баннеров, флагов и рекламных материалов для мероприятий',
            'price_info': 'от 10 000 тг/м²',
            'contact_info': 'print@fan-club.kz',
            'order': 5
        },
        {
            'title': 'Юридическая консультация',
            'service_type': 'consultation',
            'description': 'Консультация по вопросам регистрации ИП, юридического оформления сообществ',
            'price_info': '15 000 тг/час',
            'contact_info': 'legal@fan-club.kz',
            'order': 6
        },
        {
            'title': 'Бухгалтерская консультация',
            'service_type': 'consultation',
            'description': 'Помощь в ведении учета, налоговой отчетности для сообществ',
            'price_info': '12 000 тг/час',
            'contact_info': 'accounting@fan-club.kz',
            'order': 7
        },
        {
            'title': 'Нотариальные услуги',
            'service_type': 'consultation',
            'description': 'Заверение документов, договоров для сообществ и мероприятий',
            'price_info': 'по договоренности',
            'contact_info': 'notary@fan-club.kz',
            'order': 8
        },
        {
            'title': 'Студия интервью',
            'service_type': 'studio',
            'description': 'Профессиональная студия для записи интервью о ваших проектах и сообществах',
            'price_info': 'Бесплатно для участников платформы',
            'contact_info': 'studio@fan-club.kz',
            'order': 9
        },
        {
            'title': 'Сувенирная продукция',
            'service_type': 'merchandise',
            'description': 'Изготовление брендированных сувениров: кружки, ручки, брелоки',
            'price_info': 'от 500 тг/шт',
            'contact_info': 'merch@fan-club.kz',
            'order': 10
        }
    ]

    for service_data in services:
        PlatformService.objects.create(**service_data)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0002_platformservice_interviewrequest'),
    ]

    operations = [
        migrations.RunPython(create_initial_platform_services),
    ]
