# Generated by Django 5.2.8 on 2025-11-17 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0003_auto_20251118_0132'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DevelopmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория развития',
                'verbose_name_plural': 'Категории развития',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Уровень сложности')),
                ('estimated_time', models.CharField(help_text='Примерное время на освоение', max_length=50, verbose_name='Время освоения')),
                ('keywords', models.CharField(help_text='Ключевые слова через запятую', max_length=200, verbose_name='Ключевые слова')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='ai_consultant.developmentcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Навык развития',
                'verbose_name_plural': 'Навыки развития',
                'ordering': ['category', 'difficulty_level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('resource_type', models.CharField(choices=[('book', 'Книга'), ('course', 'Курс'), ('article', 'Статья'), ('video', 'Видео'), ('tool', 'Инструмент'), ('practice', 'Практика')], max_length=20, verbose_name='Тип ресурса')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Уровень сложности')),
                ('estimated_time', models.CharField(blank=True, max_length=50, verbose_name='Время на изучение')),
                ('is_free', models.BooleanField(default=True, verbose_name='Бесплатный')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемый')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ai_consultant.developmentskill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Ресурс для развития',
                'verbose_name_plural': 'Ресурсы для развития',
                'ordering': ['skill', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Название дорожки')),
                ('description', models.TextField(verbose_name='Описание')),
                ('target_audience', models.TextField(verbose_name='Целевая аудитория')),
                ('duration', models.CharField(max_length=50, verbose_name='Продолжительность')),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый')], default=1, verbose_name='Уровень сложности')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемая')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('skills', models.ManyToManyField(related_name='development_paths', to='ai_consultant.developmentskill', verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Дорожка развития',
                'verbose_name_plural': 'Дорожки развития',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='UserDevelopmentPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата начала')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('progress_percentage', models.IntegerField(default=0, verbose_name='Прогресс (%)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('development_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plans', to='ai_consultant.developmentpath', verbose_name='Дорожка развития')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='development_plans', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'План развития пользователя',
                'verbose_name_plural': 'Планы развития пользователей',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkillProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mastery_level', models.IntegerField(choices=[(0, 'Не начато'), (1, 'Начальный'), (2, 'Средний'), (3, 'Продвинутый'), (4, 'Эксперт')], default=0, verbose_name='Уровень владения')),
                ('practice_hours', models.IntegerField(default=0, verbose_name='Часов практики')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('last_practiced', models.DateTimeField(blank=True, null=True, verbose_name='Последняя практика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='ai_consultant.developmentskill', verbose_name='Навык')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_progress', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Прогресс по навыку',
                'verbose_name_plural': 'Прогресс по навыкам',
                'ordering': ['-mastery_level', 'skill'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
