# Generated by Django 5.2.8 on 2025-11-17 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0004_developmentcategory_developmentskill_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(default='💬', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#007bff', max_length=7, verbose_name='Цвет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Категория обратной связи',
                'verbose_name_plural': 'Категории обратной связи',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('suggestion', 'Предложение'), ('complaint', 'Жалоба'), ('question', 'Вопрос'), ('compliment', 'Комплимент'), ('bug_report', 'Ошибка'), ('feature_request', 'Запрос функции'), ('improvement', 'Улучшение')], max_length=20, verbose_name='Тип обратной связи')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_review', 'На рассмотрении'), ('in_progress', 'В работе'), ('resolved', 'Решена'), ('rejected', 'Отклонена'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('priority', models.IntegerField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Критический')], default=2, verbose_name='Приоритет')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email для ответа')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('page_url', models.URLField(blank=True, verbose_name='URL страницы')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('admin_notes', models.TextField(blank=True, verbose_name='Заметки администратора')),
                ('admin_response', models.TextField(blank=True, verbose_name='Ответ администратора')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ответа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='ai_consultant.feedbackcategory', verbose_name='Категория')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responded_feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Кто ответил')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(choices=[(1, '1 - Очень плохо'), (2, '2 - Плохо'), (3, '3 - Нормально'), (4, '4 - Хорошо'), (5, '5 - Отлично')], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий к оценке')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('feedback', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='ai_consultant.userfeedback', verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name': 'Оценка обратной связи',
                'verbose_name_plural': 'Оценки обратной связи',
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='feedback_attachments/%Y/%m/', verbose_name='Файл')),
                ('filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.PositiveIntegerField(verbose_name='Размер файла (байты)')),
                ('content_type', models.CharField(max_length=100, verbose_name='Тип файла')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ai_consultant.userfeedback', verbose_name='Обратная связь')),
            ],
            options={
                'verbose_name': 'Вложение к отзыву',
                'verbose_name_plural': 'Вложения к отзывам',
                'ordering': ['created_at'],
            },
        ),
    ]
