# Generated by Django 5.2.8 on 2025-11-20 23:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0006_alter_chatsession_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='ID сессии ИИ', max_length=255)),
                ('log_type', models.CharField(choices=[('user_input', 'Ввод пользователя'), ('ai_response', 'Ответ ИИ'), ('error', 'Ошибка'), ('validation', 'Валидация'), ('security', 'Событие безопасности'), ('state_change', 'Изменение состояния')], db_index=True, help_text='Тип лога', max_length=20)),
                ('message', models.TextField(help_text='Сообщение или данные')),
                ('response_data', models.JSONField(blank=True, help_text='Данные ответа (для AI responses)', null=True)),
                ('processing_time', models.FloatField(blank=True, help_text='Время обработки в секундах', null=True)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Количество использованных токенов', null=True)),
                ('stage', models.CharField(blank=True, db_index=True, help_text='Этап对话', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Лог сессии ИИ',
                'verbose_name_plural': 'Логи сессий ИИ',
                'db_table': 'ai_session_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='ai_session__session_16c018_idx'), models.Index(fields=['log_type'], name='ai_session__log_typ_5eb609_idx'), models.Index(fields=['created_at'], name='ai_session__created_6b1166_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, help_text='Уникальный идентификатор сессии', max_length=255, unique=True)),
                ('stage', models.CharField(choices=[('welcome', 'Начало создания'), ('name', 'Название клуба'), ('category', 'Категория'), ('description', 'Описание'), ('email', 'Email для связи'), ('phone', 'Телефон'), ('confirm', 'Подтверждение'), ('edit', 'Редактирование'), ('done', 'Завершено'), ('error', 'Ошибка')], db_index=True, default='welcome', help_text='Текущий этап对话', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Данные, собранные на текущем этапе')),
                ('last_question', models.CharField(blank=True, help_text='Последний заданный вопрос', max_length=100, null=True)),
                ('progress', models.IntegerField(default=0, help_text='Прогресс в процентах (0-100)')),
                ('user_agent', models.TextField(blank=True, help_text='User-Agent браузера', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес пользователя', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Время окончания жизни сессии', null=True)),
                ('user', models.ForeignKey(blank=True, help_text='Пользователь (если аутентифицирован)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Состояние对话',
                'verbose_name_plural': 'Состояния对话',
                'db_table': 'ai_conversation_states',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ClubCreationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('club_name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Успешно создан'), ('failed', 'Ошибка создания'), ('cancelled', 'Отменено')], db_index=True, default='pending', max_length=20)),
                ('club_id', models.UUIDField(blank=True, help_text='ID созданного клуба', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Сообщение об ошибке', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='creation_request', to='ai_consultant.conversationstate')),
            ],
            options={
                'verbose_name': 'Запрос создания клуба',
                'verbose_name_plural': 'Запросы создания клубов',
                'db_table': 'club_creation_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['session_id'], name='ai_conversa_session_df2063_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['stage'], name='ai_conversa_stage_8d5cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['created_at'], name='ai_conversa_created_4be1fb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['updated_at'], name='ai_conversa_updated_638293_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationstate',
            index=models.Index(fields=['expires_at'], name='ai_conversa_expires_68663e_idx'),
        ),
        migrations.AddIndex(
            model_name='clubcreationrequest',
            index=models.Index(fields=['status'], name='club_creati_status_63bea5_idx'),
        ),
        migrations.AddIndex(
            model_name='clubcreationrequest',
            index=models.Index(fields=['created_at'], name='club_creati_created_8f1376_idx'),
        ),
    ]
