# Generated by Django 5.2.8 on 2025-11-21 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0007_add_conversation_state_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='agent_context',
            field=models.JSONField(blank=True, default=dict, help_text='Данные для сохранения состояния между сообщениями', verbose_name='Контекст агента'),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_agent',
            field=models.CharField(blank=True, help_text='Имя агента, который обрабатывает текущий диалог', max_length=50, null=True, verbose_name='Текущий агент'),
        ),
    ]
