# Generated by Django 5.2.8 on 2025-11-21 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_consultant', '0008_chatsession_agent_context_chatsession_current_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationstate',
            name='stage',
            field=models.CharField(choices=[('welcome', 'Начало создания'), ('name', 'Название клуба'), ('category', 'Категория'), ('description', 'Описание'), ('city', 'Город'), ('email', 'Email для связи'), ('phone', 'Телефон'), ('confirm', 'Подтверждение'), ('edit', 'Редактирование'), ('done', 'Завершено'), ('error', 'Ошибка')], db_index=True, default='welcome', help_text='Текущий этап对话', max_length=50),
        ),
    ]
