# Generated by Django 4.2.13 on 2024-08-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='festival',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Локация'),
        ),
    ]
