# Generated by Django 4.2.13 on 2024-08-27 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_alter_festival_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceForClubs',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Наименование услуги')),
                ('description', models.CharField(max_length=200, verbose_name='Наименование услуги')),
            ],
        ),
    ]
