# Generated by Django 4.2.13 on 2024-09-04 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0003_serviceforclubs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceforclubs',
            options={'verbose_name': 'Услуга для сообществ', 'verbose_name_plural': 'Услуги для сообществ'},
        ),
        migrations.AddField(
            model_name='serviceforclubs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceforclubs',
            name='image',
            field=models.ImageField(default=None, upload_to='clubs/service_for_clubs', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='serviceforclubs',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена(KZT.)'),
        ),
        migrations.AddField(
            model_name='serviceforclubs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='serviceforclubs',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание услуги'),
        ),
    ]
