# Generated by Django 4.2.13 on 2024-09-04 08:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_alter_serviceforclubs_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceforclubs',
            name='phone',
            field=models.CharField(default='+77777777777', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+999999999'. Максимум 15 чисел.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Контактный телефон'),
            preserve_default=False,
        ),
    ]
