# Generated by Django 4.2.13 on 2024-09-09 09:29

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0007_publication_alter_serviceforclubs_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='asd'),
            preserve_default=False,
        ),
    ]
