# Generated by Django 4.2.13 on 2024-12-21 06:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0009_publication_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='phone',
            field=models.CharField(max_length=20, validators=[accounts.models.phone_regex_validator], verbose_name='Контактный телефон'),
        ),
        migrations.AlterField(
            model_name='serviceforclubs',
            name='phone',
            field=models.CharField(max_length=20, validators=[accounts.models.phone_regex_validator], verbose_name='Контактный телефон'),
        ),
    ]
