# Generated by Django 5.2.8 on 2025-11-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0010_alter_club_phone_alter_serviceforclubs_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='activities',
            field=models.TextField(blank=True, help_text='Какие мероприятия проводит клуб', verbose_name='Мероприятия'),
        ),
        migrations.AddField(
            model_name='club',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Показывать в рекомендациях', verbose_name='Рекомендуемый клуб'),
        ),
        migrations.AddField(
            model_name='club',
            name='recommendation_score',
            field=models.PositiveIntegerField(default=0, help_text='Чем выше, тем чаще клуб появляется в рекомендациях', verbose_name='Оценка рекомендаций'),
        ),
        migrations.AddField(
            model_name='club',
            name='skills_developed',
            field=models.TextField(blank=True, help_text='Какие навыки участники развивают в клубе', verbose_name='Развиваемые навыки'),
        ),
        migrations.AddField(
            model_name='club',
            name='tags',
            field=models.CharField(blank=True, help_text='Например: спорт, здоровье, развитие, технологии', max_length=500, verbose_name='Теги (через запятую)'),
        ),
        migrations.AddField(
            model_name='club',
            name='target_audience',
            field=models.TextField(blank=True, help_text='Описание идеальных участников клуба', verbose_name='Целевая аудитория'),
        ),
    ]
