# Generated by Django 5.2.8 on 2025-11-20 16:16

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0011_club_activities_club_is_featured_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubPost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='clubs.club', verbose_name='Клуб')),
            ],
            options={
                'verbose_name': 'Пост клуба',
                'verbose_name_plural': 'Посты клуба',
                'ordering': ['-created_at'],
            },
        ),
    ]
